@REM Gradle wrapper JAR is generated by Android Studio (File > Open android/).
@echo off
echo Open the android folder in Android Studio to generate the Gradle wrapper, then sync the project.
exit /b 1
